#! /bin/sh

# Plasma Theme
#export KDE_SESSION_VERSION=5
#export QT_QPA_PLATFORMTHEME=kde
xrandr --output HDMI-0 --mode 3840x2160 --rate 60
setxkbmap gb &
picom &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

QT_QPA_PLATFORMTHEME="qt5ct"

nitrogen --restore
#nice xwinwrap -b -s -fs -st -sp -nf -fdt -- mpv -wid WID --really-quiet --framedrop=vo --no-audio --panscan="1.0" /home/cieran/Downloads/back.mp4 &
${HOME}/.config/polybar/launch
gentoo-pipewire-launcher &
gentoo-pipewire-launcher restart &
